AWSTemplateFormatVersion: "2010-09-09"
Description: "Resource for CI/CD of Info106 backend"
Parameters:
  BackendRepositoryUrl:
    Type: String
    Description: "HTTPS clone URL to the repository"
Resources:
  BackendBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: BackendBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: BackendBuildPolicyStatement
                Effect: Allow
                Action: "*"
                Resource: "*"
  BackendBuild:
    Type: "AWS::CodeBuild::Project"
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      TimeoutInMinutes: 10
      ServiceRole: !GetAtt BackendBuildRole.Arn
      Source:
        GitCloneDepth: 1
        Type: GITHUB
        Location: !Ref BackendRepositoryUrl
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: HEAD_REF
              Pattern: ^refs/heads/main$
            - Type: EVENT
              Pattern: PUSH
